### ISSUE TITLE
Could inline CSS be put in the minited file?

### ISSUE THREAD

**Issue by szepeviktor** [kasparsd/minit#55]
```php
function theme_name_scripts() {
    wp_enqueue_style( 'style-name', '/static/themes/TidalForce/style.css' );
    wp_add_inline_style( 'style-name', 'a{font-weight: bold !important;}' );
}

add_action( 'wp_enqueue_scripts', 'theme_name_scripts' );
```

```css
<link rel='stylesheet' id='minit-css-css'  href='http://subtwo.wp/static/uploads/minit/c15621859a80c68d5763f1bde094dd4a.css' type='text/css' media='all' />
<style id='minit-css-inline-css' type='text/css'>
a{font-weight: bold !important;}
</style>
```
